### ISSUE TITLE
Installing multiple genres wreaks havoc with the rank catalogue

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#102]
Since the genre install doesn't wipe out what's in the database already, the system doesn't pull the proper item from the rank catalogue

**Comment by anodyne** [comment]
Will be patched in a 1.0.x release

**Comment by anodyne** [comment]
Fixed in the following commits: 91a69735955434fd57b4adc33b9078a5209a1402, 2dd095879b859b7bf89c4997e9ee231aed76bdad, d3097a54aa185e826796ff1481f7b02a4c2eeec3. This fix will be released with version 1.0.1.

**Comment by anodyne** [comment]
updated the ranks model with method fixes for handling genres in rank catalogue items (closed by d3097a54aa185e826796ff1481f7b02a4c2eeec3)

**Comment by anodyne** [comment]
Bumped to version 1.0.2

**Comment by anodyne** [comment]
updated the ranks model with method fixes for handling genres in rank catalogue items (closed by d3097a54aa185e826796ff1481f7b02a4c2eeec3)
