### ISSUE TITLE
Last author is being dropped from mission posts

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#109]
http://forums.anodyne-productions.com/viewtopic.php?f=60&t=2848

**Comment by AlPrunty** [comment]
Still happening on my end

**Comment by anodyne** [comment]
Because the fix hasn't been released.

**Comment by anodyne** [comment]
Fixed in ec35740bf571a68047a0ca1cefd8ac83c9331438. Will be released in 1.0.2.

**Comment by anodyne** [comment]
Some people are still seeing this issue in 1.0.2.

**Comment by anodyne** [comment]
Can be fixed by deleting application/controllers/base/write_base.php and application/views/_base/admin/pages/write_missionpost.php and uploading their respective copies from the Nova zip archive.
