### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#110]
http://forums.anodyne-productions.com/viewtopic.php?f=60&t=2855
http://forums.anodyne-productions.com/viewtopic.php?f=60&t=2842

**Comment by anodyne** [comment]
There may still be issues with the autologin, but so far, only one person has reported seeing it. Everything else was related to people not understanding the passwords are case-sensitive.

**Comment by anodyne** [comment]
Attempted to fix some of these issues in 94e5631b88ea87ba6c6bde27ced0236784b91577

**Comment by anodyne** [comment]
No one has reported issues when using 1.0.3, so closing this again until it pops up again, but hopefully this one is behind us.
