### ISSUE TITLE
Switching from a ship to starbase and back again.

### ISSUE THREAD

**Issue by AlPrunty** [anodyne/nova#112]
This is an issue from a fleet member:

I might believe that, if it wasn't for the fact that SMS installed with default settings and could be changed from that point.

For example, the simm type (or "genre"). In SMS, it installed as a ship (if memory serves) and I can switch it to a starbase anytime I wish by going to Site Globals and clicking a radio button.

I've been over the Nova docs, and I can't find anywhere that I can do that switch that easily. It may exist, but if it does, they've done a very good job of hiding it.

**Comment by anodyne** [comment]
It's in site settings in the general tab. There's a drop down for sim type.
