### ISSUE TITLE
Wiki doesn't load in PHP 4

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#114]

**Comment by anodyne** [comment]
Locally, Apache is crashing when it tries to load the wiki, but I don't know why. I also get get the page to stop execution if I remove all the calls to the template library, but there's nothing in the method that would be causing these kinds of issues (that I can see).

**Comment by dustin-lennon** [comment]
In the Thresher_Markdown.php is there a real need for the Wordpress and bBlog plugin stuff? I'm a bit iffy about the Smarty stuff too, don't know if that is really needed either.

**Comment by anodyne** [comment]
It's all part of the library, so I'm hesitant to remove it just for the sake of removing it.

**Comment by dustin-lennon** [comment]
Ok, curious was all.

**Comment by anodyne** [comment]
I'm fairly close to just bumping Thresher's requirements to PHP 5.

**Comment by dustin-lennon** [comment]
Here is an updated Thresher_Textile.php that I grabbed from http://textpattern.com/download as per this page http://codeigniter.com/wiki/Textile_Markup/

http://gist.github.com/386517

**Comment by anodyne** [comment]
Thanks for this. Usually around the first of every month I make a quick run through all the system components and check for new versions. MarkItUp and jQueryUI also saw some updates, so I'll include this in the next update.

**Comment by anodyne** [comment]
Upped Thresher's server requirements to PHP5 since I can't track down the bug. The change landed in d790bcfcc50b62e56359321a1d185e127ca5d3e2. Closing this now.
