### ISSUE TITLE
User-created missions for admin approval

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#122]
Now, the idea I came up with just now is to do with mission creation. Is there a possibility of adding a bit more detail into the permissions surrounding this? The idea stems from an NPC I recently thought up for a Starbase sim I'm on - a PI. Essentially, posts with this character will likely be at times disconnected from the rest of the sim, and in some cases may even involve rather large plots, which may deserve their own missions. Would there be potential for the inclusion of an option to 'assign' certain mission groups to individual uses, permitting them to create their own missions in that group regardless of what other permission settings they have? This is something that can easily be worked around, as mentioned in the paragraph above (for example, allowing a user permission to create missions generally, or having missions created via the CO), but I foresee that Starbase and Colony sims especially could find this function particularly useful.

http://forums.anodyne-productions.com/viewtopic.php?f=96&t=3040&p=17224

**Comment by anodyne** [comment]
Rejected.
