### ISSUE TITLE
Make Thresher's main page a wiki entry itself

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#123]
What I'd like to suggest, if possible, for Nova 2 is a more user-specified main page for the Thresher Wiki. I'm thinking of something that is a Wiki page in itself, much like the main page of all those MediaWiki sites out there. COs could do whatever they want with it - lay out whatever links off the main page they want, images, or whatever, and have it as neat or as utilitarian as they want.

As for what to do with the recent changes and recent creations parts, there are two options I could see for doing them; either give the CO the option in the globals somewhere for whether they want them displayed (preferably in a smaller font and such to the default) underneath their main page content, and/or having them as links in the side menu.

http://forums.anodyne-productions.com/viewtopic.php?f=96&t=3015

**Comment by agentphoenix** [comment]
Let's actually do this for all Thresher system pages. This will give people more control over intro messages for pages and what not. Should be able to do this by adding a couple fields to the wiki_pages table: protected and page_type.

**Comment by agentphoenix** [comment]
Done and done. System pages were rolled in a while back.
