### ISSUE TITLE
Dynamic form field restrictions

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#125]
It would be a great feature to be able to make some fields of a character's biography so that only an Administrator could edit it. Sort of like the rank/position settings.

http://forums.anodyne-productions.com/viewtopic.php?f=96&t=2881

**Comment by agentphoenix** [comment]
> Stephen Clark - Tue Apr 20, 2010 1:36 am
> 
> It would be a great feature to be able to make some fields of a character's biography so that only an Administrator could edit it. Sort of like the rank/position settings.
> 
> The reason being in my simulation I have certain bio fields in order to list them with the character that I'd really only like to change. It's a police department simulation and has fields such as:
> 
> Shield Number
> Serial Number
> Special Qualifications (IE: ESU Team, USAR Team, FTO, etc.)

**Comment by agentphoenix** [comment]
Added in d3da6adae80ac2266f17a8e593728fceb2087aeb

**Comment by agentphoenix** [comment]
- If the form is in edit mode...
  - and there's no data for the field, don't display the label or control
  - and there is data for the field, display the label and print the data
  - and there is data for the field and it's restricted above the current user, display the label and print the data as well as a tooltip explaining why they can't edit the value
- If the form is read mode...
  - and there's no data for the field, don't display the label or data
  - and there is data for the field, display the label and print the data

**Comment by agentphoenix** [comment]
Updated in aba67996d075aa9e40b9ef28c07598eb1f764744
