### ISSUE TITLE
Upload and add images to wiki pages

### ISSUE THREAD

**Issue by agentphoenix** [anodyne/nova#129]
http://forums.anodyne-productions.com/viewtopic.php?f=59&t=3109

**Comment by agentphoenix** [comment]
Adding the initial forum post since it'll be going away at some point.

> wisper - Sun Jul 25, 2010 8:07 am
> 
> I was wondering would it be possible to add a upload feature to the wiki? So we can upload photos to the wiki and then maybe have the option to add the code to the wiki.

**Comment by jwatte** [comment]
Seconded, thirded, etc. That would be so much easier than having to create a separate git repo for storing documentation images...

**Comment by agentphoenix** [comment]
This project is not affiliated with Github for the built-in wiki.
