### ISSUE TITLE
Quick install for ranks and skins

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#14]
We need a way to do quick installs of ranks and skins (along with their sections).

This could be accomplished by using XML files with set fields and then Nova could look for directories that aren't installed and pull those XML files to create the skin catalogue and skin section catalogue work on the fly.

**Comment by anodyne** [comment]
This has been started but there are still a few items that need to be addressed.
1. During installation, the system should loop through and install any skins
2. During installation, the system should loop through and install any ranks
3. Genre files need to be cleaned up for rank information
4. Install files need to be cleaned up for skin information
5. All rank sets in the source repo need to get the YAML files
6. All skins in the source repo need to get the YAML files

**Comment by anodyne** [comment]
This should be all set now.
