### ISSUE TITLE
Admin-forced password resets

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#16]
Admins should be able to force a user to reset their password

**Comment by agentphoenix** [comment]
Not quite what the request was asking for, but Nova 2 will allow admins to reset a user's password if they've forgotten it. Nova will generate a random password and send it to the user. The next time the user logs in, they'll be prompted to change their password to something they can remember. This changes landed in 0ce8a039932ceecc8b1e62d9f1bf7761f3162fb2.

We will not be building functionality to simply force a password reset. If a situation arises where an admin needs to do that, they can run a simple SQL query to do that.
