### ISSUE TITLE
More crew_type options

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#17]
Right now, Nova just uses active, inactive, npc and pending, but those aren't really crew types as much as types and statuses.  We should make crew_type be playing and nonplaying and status active, inactive and pending. That will allow for inactive NPCs, pending NPCs and other combinations.

**Comment by anodyne** [comment]
NPCs are really a holdover from the SMS days. The fact of the matter is, you can _play_ a non-_playing_ character. How does that make any sense? It doesn't. Moving forward, characters should have a type/status setup of active, inactive, pending and archived. A character would be listed as an NPC if they're active and don't have a user associated with them. Archived would allow characters to be removed from view but still around in the event they're associated with a post or something.
