### ISSUE TITLE
Manually sorting mission posts

### ISSUE THREAD

**Issue by agentphoenix** [anodyne/nova#176]
> LeiYong Sat Mar 31, 2012 11:30 pm
> 
> I would like to ask if its possible to reorder your posts in Nova 3. Considering that you want to change the Location and Timeline fields [I repeat them within the content of the post anyway], it would be nice if we could change the order so as to reflect a continuity of the story correctly. [Instead of backposts for those posts occuring before the present time of the simm story]

**Comment by agentphoenix** [comment]
> **My Reponse**
> 
> The trick with this comes in with how inefficient it is. Think about it: you have to store a manual order field and keep it accurate (which would be tricky enough given the highly dynamic nature of a system like Nova), but then when you re-order items, things get out of control quickly.
> 
> Let's assume you have a mission with 100 posts in it. At the end of the mission, people started backposting to before the mission began to fill in some gaps. You want those posts to appear before the mission start post, so you click and drag one of the items to the top of the list. Because there's a manual order column there, now **every single post** from the top to the bottom has to be updated. You're talking about running 100 queries against the database just to move one post like that. Highly inefficient. That only gets worse the more items are in the mission. Imagine if you have 200, 300, 500 posts, now you're talking about it take 60 seconds to refresh that page.
> 
> It's certainly possible, but I'm not sold on the _way_ to do it. For now, I'd have to say no, but it's in the issue tracker as a feature request, so if I can come up with a better way to handle it, I'll see about putting it in.

**Comment by agentphoenix** [comment]
We may actually be able to move the posts over to a nested sets format that will do this type of interaction for us. Doing more research to find out if it's plausible.

**Comment by mooeypoo** [comment]
Just an idea here - I was thinking about a Nova2 mod for this that would simply allow the user to change the posting date (like you can do with posts in Wordpress) so you can post something "in the past", and maintain continuity with backlogs. This might be easier than creating a custom order from scratch.

**Comment by agentphoenix** [comment]
That works as a MOD, but isn't a very good permanent solution, which is why I've looked into use a nested sets model in the future. Anything that I work on will be for Nova 3, so Nova 2 will have to rely on MODs to accomplish this.
