### ISSUE TITLE
core/controllers/nova_personnel.php

### ISSUE THREAD

**Issue by dustin-lennon** [anodyne/nova#208]
Lines 811 and 812 have visible var_dumps. Weren't commented out prior to release.

**Comment by agentphoenix** [comment]
This was also addressed on the forums.

http://forums.anodyne-productions.com/viewtopic.php?f=60&t=3785

Additionally, this has already been fixed on the develop branch in aaa8e1a78866f606abbe9a4ea837d0828aa4253d.
