### ISSUE TITLE
info.php still shows 2.1.0 instead of 2.1.1 causes a update message in nova

### ISSUE THREAD

**Issue by Arthius** [anodyne/nova#209]

**Comment by agentphoenix** [comment]
Dammit. My bad. I'll re-generate all the zip files so this isn't an issue.

**Comment by Arthius** [comment]
When I noticed figured I should let you know lol 

----- Reply message -----

**Comment by agentphoenix** [comment]
Yep, definitely. Thanks for the heads up!
