### ISSUE TITLE
Email templates not included in default or titan skins on new installs

### ISSUE THREAD

**Issue by dustin-lennon** [anodyne/nova#210]
I had someone submit to me a bug report about their emails being blank on a fresh install of nova when they installed one of my mods. I did some research and found that the default and titan skins don't have an emails folder included with the install. I forget, have these ever been available or have these needed to be created by the site admin?

**Comment by agentphoenix** [comment]
Are you talking about emails from the core or emails from your mods?

**Comment by dustin-lennon** [comment]
I'm talking emails from the core such as logs. Here is a copy of the bug report I received. 

> Hello,
> 
> I've used this mod in the past on other sites without an issue, and it continues to work perfectly on those sites which were updated from previous versions.
> 
> However, I've got a new install which I'm trying to get set up and for some reason the Mod doesn't send the content of the personal log in the email.
> 
> I have no other mods to the write.php file. Just this one.
> 
> It does show the personal log test data on the site, it displays just fine. It just doesn't seem to be including the content text in the email it sends out..
> 
> Help?

**Comment by agentphoenix** [comment]
You're still talking about something that happens when a mod is installed. Do the emails work as expected _before_ the mod is installed?

**Comment by dustin-lennon** [comment]
yes, so disregard. I'll have to investigate further to see what's going on with my bug report for my mod

**Comment by agentphoenix** [comment]
We can leave this issue open in case you have any questions when it comes to making changes to your mod. Once you figure it out, go ahead and close this.

**Comment by dustin-lennon** [comment]
Ok
