### ISSUE TITLE
Creating 1st mission on vanilla install of nova 2.1.1

### ISSUE THREAD

**Issue by dustin-lennon** [anodyne/nova#211]
Went to set up a mission on my vanilla install of nova 2.1.1 and was presented with the dialog box to create my first mission. I input data in all fields, yet mission wouldn't be created. Only way to successfully create the very first mission was to go through the manage missions interface. Are there some required fields that are not in that dialog box that comes up when you click "Write mission post" and have no missions set up yet?

**Comment by agentphoenix** [comment]
I can't duplicate this issue. I was able to enter the details in the pop-up and have a mission created on the fly.
