### ISSUE TITLE
Challenges with BR in Theme Building

### ISSUE THREAD

**Issue by jonmatterson** [anodyne/nova#212]
The `br` element is not particularly semantic. As I'm working on a Bootstrap-based theme for Nova, I'm finding myself having to do two `br`-related tasks over and over:
1. Create template pages views simply to remove `br` elements from the markup that create excess spacing
2. Wrapping things generated by `nl2br` and `text_output` in a custom utility function that transforms multiple `br` elements into paragraphs where it makes sense.

For context, the helper function I'm using is the following:

``` php
    public static function br2p($text)
    {
        $text = explode('<br />', $text);
        $last_empty = true;
        $out_of_p = false;
        $str .= '<p>';
        foreach($text as $sub)
        {
            $len_0 = (strlen(trim($sub)) == 0);

            if($len_0)
            {
                if(!$out_of_p)
                    $str .= '</p>';
                else
                    $str .= '<br>';
            }
            else
            {
                if($out_of_p)
                {
                    $str .= '<p>';
                    $out_of_p = false;
                }
                elseif(!$last_empty)
                {
                    $str .= '<br>';
                }
                $str .= $sub;
            }

            if($len_0)
                $out_of_p = true;

            $last_empty = $len_0;
        }
        $str .= '</p>';
        return $str;
    }
```

Admittedly, I'm as guilty as anyone else for putting `br` elements in the code, since they were the primary way spacing was done all the way back to SMS 1.2. If it would be useful, I'd be happy to put some fixes in a branch for a pull request against Nova 2.1.

**Comment by agentphoenix** [comment]
Honestly, I'm too concerned about it in Nova 2. Nova 3 is being built entirely off of Bootstrap and a lot of these issues have been fixed. If you want to make changes in a branch and do a PR, that's fine. I can take a look at things and if it works, merge the changes.

**Comment by jonmatterson** [comment]
Sounds good :-) go ahead and assign this issue to me?

**Comment by agentphoenix** [comment]
The biggest issue here is going to be that your updates will require changes to every skin out there, be it created by Anodyne or created/modified by someone else. I'm gonna need to think about the best release strategy for something like this...

**Comment by jonmatterson** [comment]
@agentphoenix yeah that's a tricky bit on this. Maybe hold off it until Nova 2.2?

The first commit referenced here (0ec0a96) shouldn't break anything except that it may change the line spacing in the middle of text blocks. All it does is take multiple instances of `br` as fed to the `text_output` method (when a `p` tag or no tag at all is set as the param) and transforms them so that two `br` tags in a row becomes a new paragraph while a single `br` is left as a single `br`. In the event that there are more than two `br` tags in a row with only whitespace, then it will leave the extra `br` tags alone. This is kind of similar to what a lot of Markdown parsers do (except they go straight from newline format to br-p format while, in trying to change as little as possible with existing code, I'm going newline to br to br-p).

The second commit (86b9acd), though, could certainly break styles if they rely on the spacing provided by `br` (such as negative margins on follow up elements or image-based designs in the background that require a certain spacing). Note that this was only intended as a partial commit based on what I needed to far - I'll create some more commits linked to this issue as I continue along this vein and I'll let you know when I think I've hit them all.

As a side note, I'm probably also going to be adding some additional classes to certain elements (this shouldn't break anything) to make them more targetable for skinning - my goal with this last bit is to cut down on how often a skin builder needs to redefine a page view (which could be a nightmare for upgrades to future versions). I'll tag those commits with this issue number as well.
