### ISSUE TITLE
Add reply to functionality on emails from Nova

### ISSUE THREAD

**Issue by agentphoenix** [anodyne/nova#217]
All of the email calls should have the `reply_to` flag set to who the submitter is. Still up on the air about whether to do this at all in 2.x.

**Comment by dustin-lennon** [comment]
Would these replies post to nova as the respected item as a comment?

**Comment by agentphoenix** [comment]
Nope. Would just respond back to the sender.

**Comment by dustin-lennon** [comment]
Ah, ok

**Comment by dustin-lennon** [comment]
So if I were to post a news item from address being nova@sto.ucip.org it would be the email address associated with my account?

**Comment by agentphoenix** [comment]
Huh?

**Comment by dustin-lennon** [comment]
what I am saying is that if I for example post a news item, the current email header  is

> from:  FADM Dustin Shea nova@sto.ucip.org
> reply-to:  "nova@sto.ucip.org" nova@sto.ucip.org
> to:    demonicpagan@gmail.com
> date:  Mon, Nov 5, 2012 at 3:44 PM
> subject:   [Startrek Online UCIP Fleet] General News - Welcome!
> mailed-by:     sims.ucip.org

reply-to would use the email address associated with my account, demonicpagan@gmail.com

**Comment by agentphoenix** [comment]
Correct. Not sold on that change yet though.

**Comment by agentphoenix** [comment]
efb59472a5396d6437b437eda84af453ca7a25c8
