### ISSUE TITLE
Laravel 4 evaluation

### ISSUE THREAD

**Issue by agentphoenix** [anodyne/nova#225]

**Comment by agentphoenix** [comment]
Laravel 4 beta (with documentation) is coming this week. This should help clear up some of the questions that have crept up over the last couple of months. With these questions out of the way, we'll better be able to make a decision about whether this is the right path for Nova 3.

**Comment by jonmatterson** [comment]
Definitely looking forward to the beta _with documentation_.

**Comment by agentphoenix** [comment]
@jonmatterson I was shocked when Taylor tweeted that out the other day. So rare for a beta to be accompanied by full documentation!

**Comment by agentphoenix** [comment]
Laravel 4 it is!

I've been doing a bunch of work with it and I think it offers us the best foundation. There's gonna be some work to do to make sure things work as expected, but nothing that can't be overcome.
