### ISSUE TITLE
Edit in place

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#25]
It'd be nice to have some sort of edit in place functionality for ranks, positions, departments, etc that relies heavily on AJAX calls and whatnot

http://net.tutsplus.com/tutorials/javascript-ajax/create-an-in-place-editing-system/

**Comment by agentphoenix** [comment]
Using this: http://www.appelsiini.net/projects/jeditable

**Comment by agentphoenix** [comment]
Mostly finished. Will need some more testing.
