### ISSUE TITLE
Manually add a user to the system

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#28]
http://forums.anodyne-productions.com/viewtopic.php?f=88&t=2690

**Comment by agentphoenix** [comment]
> Vorn Krace - Sun Oct 18, 2009 7:09 pm
> 
> Next, is a bit more of a feature request/enquiry than a bug. Will there be, in a future version of Nova, the ability to add a user manually? Unless I've missed it, an Admin can add characters, but not users, which makes life that bit more complicated if you're in a fleet which allows users to apply through its own join forms (such as IFS), and you want to save the time from waiting for them to then sign up at your site, and add them manually.

**Comment by agentphoenix** [comment]
Will be addressed in #190

**Comment by agentphoenix** [comment]
Completed in f5c3342388596d4aa63ce361564c5a98d9194920
