### ISSUE TITLE
LOA Monitoring Issue

### ISSUE THREAD

**Issue by greenfelt22** [anodyne/nova#294]
The clock LOA Records report does not end whenever a user returns from LOA. The page lists a start time and expected duration for the LOA, but does not list the actual end time.

**Comment by ITHedgeHog** [comment]
I'm taking a look in to this.

**Comment by agentphoenix** [comment]
@greenfelt22 Thanks for the report. Can you please post the screenshots you shared in Discord?

**Comment by greenfelt22** [comment]
![image](https://user-images.githubusercontent.com/25126048/92532372-c4d81b00-f1f5-11ea-87c1-24771ee4d62a.png)

![image](https://user-images.githubusercontent.com/25126048/92532389-cacdfc00-f1f5-11ea-84e1-f9894d55e200.png)

**Comment by agentphoenix** [comment]
@greenfelt22 I haven't been able to reproduce this. If you have specific steps to take, I'll be happy to look at it again.
