### ISSUE TITLE
Creating a mission without a start or end date does not give good error messages

### ISSUE THREAD

**Issue by captain118** [anodyne/nova#296]
If you attempt to create a mission and do not specify the start or end date you get a sql query error that does not state what the problem is.  I checked the table and those fields are not required.  It would be nice if at least the end date was optional.  If nothing else it would be good to have better error messages.

**Comment by agentphoenix** [comment]
@captain118 Can you please provide the error message and a screenshot of what happens?

**Comment by captain118** [comment]
Is there a private way I can send it to you?  The error message has info in it that I'd rather not share.

**Comment by agentphoenix** [comment]
You can DM me on Discord @captain118

**Comment by agentphoenix** [comment]
Fixed in 29a55892a9b78a055d06dd88ad4235f68777bb7f. Will be released with Nova 2.7.
