### ISSUE TITLE
Secondary manifests

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#3]
## Database Schema

**nova_manifests**
- manifest_id
- manifest_name
- manifest_desc
- manifest_order
- manifest_display

**nova_manifests_depts**
- mdept_id
- mdept_manifest
- mdept_dept

**nova_manifests_characters**
- mchar_id
- mchar_manifest
- mchar_character
## Process
1. grab the departments from the manifests_depts table and get all the
   departments for the manifest being requested from the uri. loop through the
   departments and if the department is in the manifest department array, keep going
2. grab the characters from the manifests_characters table and get all the
   characters for the manifest being requested from the uri. loop through the characters
   and if the character is in the manifest characters array, keep going

**Comment by agentphoenix** [comment]
Resolved in the following commits: 
- b037808589d83b729bf3
- 4864cc0690c723c9fede
- 490e5833dc51e616b5db
- 07c123bfea1f6467f958
- bf1cf387a6e0f3315345

**Comment by agentphoenix** [comment]
Still need to come up with better ways to handle department and position management as well as listing departments.
