### ISSUE TITLE
Blank Page during upgrade from 2.7.8 to 2.7.9

### ISSUE THREAD

**Issue by diziara** [anodyne/nova#304]
Upgrade appears to have completed correctly — no errors found on Nova post upgrade — but during the upgrade process from 2.7.8 to 2.7.9 a blank page is returned instead of what was probably supposed to be the upgrade complete page.

Version: STO
Browser: Firefox Developer Edition Linux 124.0b9 (64-bit)

**Comment by agentphoenix** [comment]
@diziara I haven't seen those, but let me know if you see the same issue with the 2.7.10 update and if there are any error logs that might indicate what's happening

**Comment by diziara** [comment]
It didn't reoccur with this upgrade. Everything went as smooth an a greased Scotsman in a jefferies tube.

**Comment by agentphoenix** [comment]
@diziara Awesome. Closing this, but let me know if you see any other issues.
