### ISSUE TITLE
RSS Feeds have inaccurate timestamps

### ISSUE THREAD

**Issue by TurqW** [anodyne/nova#305]
PHP "helpfully" slaps a time zone indicator onto the timestamps in the RSS feed:

`'Sun, 17 Mar 2024 23:51:56 -0700'`

However, these timestamps appear to be stored in UTC in the database, and have not been converted in any way, meaning that (in this case) the timestamp is actually off by 7 hours, which can mess up feed readers.

**Comment by agentphoenix** [comment]
Closed by #307
