### ISSUE TITLE
Mobile template and views

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#39]
We should consider adding some kind of mobile support for Nova in a future update.  We can just tap in to seamless substitution and if it's a mobile browser, use the mobile template and mobile views.

**Comment by agentphoenix** [comment]
Started work on this today on a limited basis. Will stay fairly restricted for now but Nova 3 may expand on it more.

**Comment by agentphoenix** [comment]
This won't be added to the 2.2 release since it's a tentpole feature of Nova 3.
