### ISSUE TITLE
Base model used for all the models (PHP 5 only)

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#56]
It'd be awesome to move over to a base model that every model can extend.  By making them more generic, we can actually cut down on the number of model methods being used.

http://igniteyourcode.com/productivity/practical-models/
http://jamieonsoftware.com/blog/entry/better-controllers-and-models-in-codeigniter

**Comment by anodyne** [comment]
Rejected. Using an ORM instead of base models.
