### ISSUE TITLE
Upgrade script throws error during step 14

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#57]
A Database Error Occurred

Error Number: 1054

Unknown column ' = ''' in 'where clause'

UPDATE `nova_users` SET `skin_main` = 'default', `skin_admin` = 'default', `skin_wiki` = 'default', `display_rank` = 'default' WHERE ` = ''

**Comment by anodyne** [comment]
Fixed in bc272deab18117cecb694eeb4d04b009f1817dff
