### ISSUE TITLE
Auto-login throws an error when going to the site again

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#58]
Nova throws the following error: The filename provided does not exist in /home/transce2/public_html/Ghosts/application/views. Remember to include the extension if other than ".php"

**Comment by anodyne** [comment]
Neither Ward or myself can duplicate this issue.

**Comment by anodyne** [comment]
Finally tracked this one down!  Fixed in e155c97c3c3f3978b3e97b3029646cccc408adf3
