### ISSUE TITLE
Create wiki categories on the fly

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#64]
Currently, Thresher doesn't allow users to create categories on the fly.  We might need to change that to allow categories to be created from typing entries.  This would mean anyone can create categories, but managing categories would still happen by those with the proper permissions.

**Comment by agentphoenix** [comment]
Will happen as part of the work on #137

**Comment by agentphoenix** [comment]
Got this working in 4259d7c9f329ee04254d821ffdfafd6322d55e0c
