### ISSUE TITLE
Lightness skin throws an error in the main section

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#66]
Message: Undefined property: MY_Loader::$posts
Filename: lightness/template_main.php
Line Number: 123

Fatal error: Call to a member function get_post_list() on a non-object in /Users/DVS/Sites/nova/code/application/views/lightness/template_main.php on line 123

**Comment by anodyne** [comment]
Fixed.

CI apparently won't allow you to load a model in the view and use it.
