### ISSUE TITLE
Confirm password field on the join form

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#67]
http://forums.anodyne-productions.com/viewtopic.php?f=88&t=2758

**Comment by agentphoenix** [comment]
> Swimminschrage - Sat Jan 23, 2010 7:31 pm
> 
> I wouldn't necessarily consider this a bug, but is it possible to add a "Confirm Password" box whenever a user signs up (or even during initial character creation)? It helps prevent characters from being created even though a password may have been typed wrong (bad caps lock...bad).
