### ISSUE TITLE
Form validation on the join form

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#68]
This is going to require a new field in the database as well as some work on the form management side as well.

**Comment by agentphoenix** [comment]
This is actually really complicated, so we're pushing this out to the future ... maybe.

**Comment by agentphoenix** [comment]
Added in b6de5c941de55d7377b674227c00441d8b576527

This isn't a full-blown validation solution, but just ensures that some of the key fields have something in them. Doing a full-blown validation on every field would be _incredibly_ complicated. We may revisit that in the future, but for now, this should do just fine.
