### ISSUE TITLE
Need mechanism to choose which character to edit after using My Bio link

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#73]
When you click on My Bio, it doesn't pass a character ID into the URL, so it automatically uses the session's main character ID.  However, if you have more than one character, there needs to be a way for you to select which character you want to edit.

http://forums.anodyne-productions.com/viewtopic.php?f=88&t=2770

**Comment by anodyne** [comment]
Fixed in 085915c843d1d802186fa0c1adf17c3563d50ee1

**Comment by anodyne** [comment]
Still not fixed.

**Comment by anodyne** [comment]
Fixed in 7ebf85c5df826de58b3f5739b97b3def903de449
