### ISSUE TITLE
Nova can't make a successful XML-RPC connection

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#76]
When attempting to register, Nova can't make an XML-RPC connection to anodyne-productions.com and therefore can't finish the registration process.  Need to troubleshoot why that is and fix it for 0.9.7.

**Comment by anodyne** [comment]
It helps if the register method is uncommented.

**Comment by anodyne** [comment]
Fixed in the following commits:
- d4141bf9af62aa5a718edbb1ede77ce264816d25
- 1c1f78a05060ae21f608235abe9a0ba98ce43a6f
- 2e8c11cb82296bf6f6c8f9b57f6d86c92106d37c
