### ISSUE TITLE
Mission groups

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#85]
Mission groups is a way to group your missions together. This can be for something as simple as a series of missions that are related to more complex things like an arc of missions spread across a wide number of missions. Missions wouldn't be displayed any differently except for a "Part of..." label underneath the mission title.  (We'd need a way to show mission groups as well.)
## Schema
- misgroup_id
- misgroup_order
- misgroup_name
- misgroup_desc

**Comment by anodyne** [comment]
Changes to the missions table:
- mission_group (corresponds to the _misgroup_id_ field)

**Comment by anodyne** [comment]
Checked in with the following commits:
- Database schema - c41b0201f14648875d5ab8a61ed6633e02940b6b
- Model methods - 3cf85834fb14e0189a33bf0f4d394f4ec8552393
- System view file fixes - 18e090c3208b0f11fc1aa42ec2a66a2cf5751d22
- Displaying groups - de0337d7584548c804dc2aadaf3d5caa1d39f029
- Managing groups - b0f0351afd453d940103eaf90a1b68dc0a6ff3ee
