### ISSUE TITLE
Rendering <img src> tags

### ISSUE THREAD

**Issue by AlPrunty** [anodyne/nova#89]
I am using the following instruction in my welcome page message

<img src="/images/herc-1.jpg" align="left" hspace="10" />The USS Hercules

--- When it renders the image the 10 pixel horizontal space is not spacing it out.

the source code from the browser is...

<p><img src="/images/herc-1.jpg" align="left" hspace="10" />

It's there, but the browser is not responding to it.

My site is http://hercules.starfleetuk.org

**Comment by anodyne** [comment]
The use of hspace is deprecated in XHTML and not allowed in documents with a strict doctype. Nova templates use XHTML 1.1 (which only has a strict doctype) so using hspace won't work. The link below has more information about these types of restrictions:

http://docs.aptana.com/docs/index.php/About_using_a_Strict_vs._Transitional_DOCTYPE_in_HTML

You'll need to either assign a class to it, or, more likely, manually set the paddings around the image. This link has more information:

http://www.w3schools.com/TAGS/att_img_hspace.asp

**Comment by AlPrunty** [comment]
Learned something... I substituted  style="margin-right: 1em" for the hspace statement and got more of the effect that I desired.  Most of my HTML is old school styles... I have not kept up with what has been depreciated and what hasn't.

Thanks for teaching this old dog a new trick.
