### ISSUE TITLE
Lock joint posts while editing

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#9]
http://forums.anodyne-productions.com/viewtopic.php?f=3&t=2418&p=13850

**Comment by anodyne** [comment]
http://forums.anodyne-productions.com/viewtopic.php?f=59&t=3007

**Comment by agentphoenix** [comment]
> Johnathon - Fri Mar 13, 2009 7:04 pm
> 
> Hello 
> 
> Sorry if this one's already been asked for! I've twice now had the experience on a busy, JP oriented station, of editing and saving a JP, to have my changes lost as someone else was editing the same JP at the same time as me. I've also seen a single post sent out twice, because 2 people posted about a minute apart

And another one...

> Redhawk - Wed May 26, 2010 4:27 pm
> 
> I've found that I can go in and edit a post I'm on at the same time as another. Depending on who saves first, the other loses their edits or additions.
> 
> Maybe some sort of restriction can be added into future versions, something that will tell the second person going in that the file is currently being edited, and to check back in a few minutes...?
