### ISSUE TITLE
Tables not updated

### ISSUE THREAD

**Issue by AlPrunty** [anodyne/nova#90]
I downloaded the latest build, placed into maintainence and run the index/upgrade script.

Said no upgrades are available and my tables are still 0.9.8 instead of 0.9.9

Did I do something wrong or something didn't happen as it should?

Thanks

Allen

**Comment by anodyne** [comment]
Update files aren't finalized and put into the workflow until an official release is finalized. You can't use the update system to update between commits of the repository.
