### ISSUE TITLE
Deck listing Ajax issues

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#93]
When I add a deck after adding a few, ie I added 22 decks then needed to go add in saucer decks [ie deck 10 - saucer] and engineering decks since a few overlap, I have to go back out then come back to the deck listing page before I can move it up or it doesn't update.

**Comment by anodyne** [comment]
One letter.  One letter.  Incredible.

**Comment by anodyne** [comment]
Fixed in 69022fc6fa21b422d6adadab1b6b38aafdc2fca6
