### ISSUE TITLE
Using character images textarea has issues

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#95]
Removing any item from the textarea manually stops the click event from visibly adding the image to the textarea, but Firebug shows they're still being added to the textarea.

**Comment by anodyne** [comment]
The best option here is going to be to re-do the management of file uploads to use Ajax and sortable items.

**Comment by anodyne** [comment]
Character and mission code should be in place. Tour still needs to be done. Awards aren't being done because it only allows a single image.

**Comment by anodyne** [comment]
Landed in the following commits
- Tour - 706851379387d2dedfdb7acad0568d349feb39dd
- Missions - 5880b38aee65e3df68fc6ec173a14b60abbafe8a
- Characters
  - a81af1160225f803a8ff86843a1a224e949d9225
  - 177f2e5bb3acbf807b5cf383544ccf99b571be39
