### ISSUE TITLE
Still having issues with Joint Posts

### ISSUE THREAD

**Issue by AlPrunty** [anodyne/nova#96]
It is dropping people from the JP or you go in and they are there twice.

The person who is most intregal to the JP is often the one who has no access to edit the JP.

Allen

**Comment by AlPrunty** [comment]
People who are involved in a joint post can not see it in their control panel.  I initiated the post and see their characters there... but they can not see it!!!!

**Comment by anodyne** [comment]
I need more information. How many people are involved? How many are playing characters and how many are NPCs? Is it usually the same people? If they go directly to the post page, does it reject them? I've had no issues so you have to give me a verified test case to reproduce the issue.

**Comment by AlPrunty** [comment]
Three characters one NPC.  Send me an e-mail to allen@alprunty.com and I will give you passwords and logins for two problem accounts.

One account has to Characters and an NPC involved the other has One character.

It's the account with one character that's not getting it.

Allen

**Comment by anodyne** [comment]
Can this issue be reproduced with an official build?

**Comment by AlPrunty** [comment]
I am using your daily builds here.  I will gladly give you passwords and access to the effected accounts.  Are those considered "official"

**Comment by anodyne** [comment]
There's no such thing as daily builds. Anything that hasn't been officially packaged is not considered official. You need to confirm it's still a bug using the code from the following link. Delete all the Nova files and try again using these files.

http://dl.dropbox.com/u/2681990/nova/nova_0_9_8_ds9.zip

**Comment by anodyne** [comment]
Was able to track it down. Working on a fix.

**Comment by anodyne** [comment]
Fixed in b07ad6f9bb258f9d19af1adc145bd12469e6ef31.

Will be pushed to the repo later tonight.
